### ISSUE TITLE
compile error on virtual machine

### ISSUE THREAD

**Issue by dengshaochun** [hit9/statsd-proxy#15]
hello, when I compile on the virtual machine and got under error, 
`$ make
make  all-am
make[1]: Entering directory `/opt/statsd-proxy'
gcc -DHAVE_CONFIG_H -I.    -std=c99 -D_GNU_SOURCE -g -O2 -MT src/statsd_proxy-buf.o -MD -MP -MF src/.deps/statsd_proxy-buf.Tpo -c -o src/statsd_proxy-buf.o `test -f 'src/buf.c' || echo './'`src/buf.c
mv -f src/.deps/statsd_proxy-buf.Tpo src/.deps/statsd_proxy-buf.Po
gcc -DHAVE_CONFIG_H -I.    -std=c99 -D_GNU_SOURCE -g -O2 -MT src/statsd_proxy-cfg.o -MD -MP -MF src/.deps/statsd_proxy-cfg.Tpo -c -o src/statsd_proxy-cfg.o `test -f 'src/cfg.c' || echo './'`src/cfg.c
mv -f src/.deps/statsd_proxy-cfg.Tpo src/.deps/statsd_proxy-cfg.Po
gcc -DHAVE_CONFIG_H -I.    -std=c99 -D_GNU_SOURCE -g -O2 -MT src/statsd_proxy-config.o -MD -MP -MF src/.deps/statsd_proxy-config.Tpo -c -o src/statsd_proxy-config.o `test -f 'src/config.c' || echo './'`src/config.c
mv -f src/.deps/statsd_proxy-config.Tpo src/.deps/statsd_proxy-config.Po
gcc -DHAVE_CONFIG_H -I.    -std=c99 -D_GNU_SOURCE -g -O2 -MT src/statsd_proxy-ctx.o -MD -MP -MF src/.deps/statsd_proxy-ctx.Tpo -c -o src/statsd_proxy-ctx.o `test -f 'src/ctx.c' || echo './'`src/ctx.c
src/ctx.c: In function ‘ctx_init’:
src/ctx.c:161: error: ‘SO_REUSEPORT’ undeclared (first use in this function)
src/ctx.c:161: error: (Each undeclared identifier is reported only once
src/ctx.c:161: error: for each function it appears in.)
make[1]: *** [src/statsd_proxy-ctx.o] Error 1
make[1]: Leaving directory `/opt/statsd-proxy'
make: *** [all] Error 2`

**Comment by hit9** [comment]
Hello , it requires Linux 3.9+.

**Comment by dengshaochun** [comment]
thanks, when i use Linux 3.10.0 , Compiled successfully!
