### ISSUE TITLE
default aggregated packet is huge

### ISSUE THREAD

**Issue by vbichov** [hit9/statsd-proxy#17]
the following defaults make no sence
https://github.com/hit9/statsd-proxy/blob/3cd0297679ec9c1776a165db95fe74d2683908fb/src/proxy.h#L19

I guess this what causes #14 

changing to something more sane (like MTU) or at lieast making it configurable would be nice

**Comment by hit9** [comment]
Thanks for @islue 's pr #19  , this value is configurable now.
