### ISSUE TITLE
How to check if it's running? 

### ISSUE THREAD

**Issue by Reifier** [hit9/statsd-proxy#7]
I have it configured and running as follows: 

> 2016-05-14 09:33:00.360 debug statsd-proxy[37] load config.port => 8125
> 2016-05-14 09:33:00.360 debug statsd-proxy[37] load config.num_threads => 4
> 2016-05-14 09:33:00.360 debug statsd-proxy[37] load config.flush_interval => 10ms
> 2016-05-14 09:33:00.360 debug statsd-proxy[37] load config.node#1 udp://ip.of.statsd:8125:1
> 2016-05-14 09:33:00.360 debug statsd-proxy[37] config load done.
> 2016-05-14 09:33:00.361 info statsd-proxy[38] serving on udp://127.0.0.1:8125..
> 2016-05-14 09:33:00.361 info statsd-proxy[39] serving on udp://127.0.0.1:8125..
> 2016-05-14 09:33:00.361 info statsd-proxy[40] serving on udp://127.0.0.1:8125..
> 2016-05-14 09:33:00.361 info statsd-proxy[41] serving on udp://127.0.0.1:8125..
> 
> port 8125
> num_threads 4
> flush_interval 10  # ms
> 
> node ip.of.statsd:8125:1

How do I check if it actually accepting metrics? I tried what is recommended for js implementation: 

> echo "deploys.test.myservice:1|" | ncat -w 1 -u 127.0.0.1 8125
> Ncat: Connection refused.

However, when I: 

> ncat 127.0.0.1 8125 -v -u
> Ncat: Version 6.47 ( http://nmap.org/ncat )
> Ncat: Connected to 127.0.0.1:8125.

I run it inside the docker container on coreos.

**Comment by hit9** [comment]
Sorry but I don't get your meaning?

**Comment by Reifier** [comment]
Something like this http://dev.nuclearrooster.com/2011/05/11/sending-metrics-to-statsd-from-bash/
Shouldn't it work on proxy as well?

**Comment by Reifier** [comment]
Sorry to disturb you. That was misconfiguration on my part. It works as expected now.
